import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";
import CheckoutContextProvider from "@/contexts/checkout-context";

const primaryFont = Inter({
  subsets: ["latin"],
  variable: "--font-primary",
});

const secondaryFont = localFont({
  src: "../fonts/molde-condensed-bold.ttf", // Path to your font file
  display: "swap",
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Project LIBRARY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CheckoutContextProvider>
      <html
        lang="en"
        className={`${primaryFont.variable} ${secondaryFont.variable}`}
      >
        <body>
          <main>{children}</main>
          <Toaster />
        </body>
      </html>
    </CheckoutContextProvider>
  );
}
