import { Toaster } from "@/components/ui/sonner";
import KioskContextProvider from "@/contexts/kiosk-context";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";

const primaryFont = Inter({
  subsets: ["latin"],
  variable: "--font-primary",
});

const secondaryFont = localFont({
  src: "../fonts/molde-condensed-bold.ttf", // Path to your font file
  display: "swap",
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Project LIBRARY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <KioskContextProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={`${primaryFont.variable} ${secondaryFont.variable}`}
      >
        <body>
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main>{children}</main>
            </ThemeProvider>
          </ClerkProvider>
          <Toaster />
        </body>
      </html>
    </KioskContextProvider>
  );
}
